# Generated by Django 5.0.4 on 2025-02-26 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_last_deposit_user_last_withdrawal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_deposit',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_withdrawal',
            field=models.CharField(default='N/A', max_length=100),
        ),
    ]
