# Generated by Django 5.0.3 on 2024-04-05 08:49

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Duration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration_days', models.PositiveIntegerField()),
                ('percentage_return', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='StakePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minimum_stake_amount', models.DecimalField(decimal_places=4, max_digits=20)),
                ('maximum_stake_amount', models.DecimalField(decimal_places=4, max_digits=20)),
                ('active', models.BooleanField(default=True, help_text='Still allow stakers or not')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Stake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stake_amount', models.DecimalField(decimal_places=4, max_digits=20)),
                ('estimated_return', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('stake_status', models.CharField(choices=[('ongoing', 'Ongoing'), ('lost', 'Lost'), ('won', 'Won')], default='ongoing', max_length=50)),
                ('stake_outcome', models.CharField(choices=[('win_stakes', 'Win Stakes'), ('loose_stakes', 'Loose Stakes')], default='loose_stakes', editable=False, help_text='Determine if Trader will loose or win stakes', max_length=50)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('stake_duration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stake_duratin', to='stake.duration')),
            ],
        ),
    ]
