# Generated by Django 5.0.3 on 2024-04-05 08:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('currency', '0001_initial'),
        ('stake', '0001_initial'),
        ('wallet', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='stake',
            name='staking_wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stake_wallet', to='wallet.wallet'),
        ),
        migrations.AddField(
            model_name='stake',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staker', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stakeplan',
            name='coin',
            field=models.OneToOneField(limit_choices_to={'is_crypto': True}, on_delete=django.db.models.deletion.CASCADE, related_name='coin_stake', to='currency.currency'),
        ),
        migrations.AddField(
            model_name='stakeplan',
            name='durations',
            field=models.ManyToManyField(to='stake.duration'),
        ),
        migrations.AddField(
            model_name='stake',
            name='stake_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stakes', to='stake.stakeplan'),
        ),
    ]
