# Generated by Django 5.0.4 on 2025-01-23 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stake', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stake',
            name='estimated_return',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='stake',
            name='stake_amount',
            field=models.DecimalField(decimal_places=8, max_digits=20),
        ),
        migrations.AlterField(
            model_name='stakeplan',
            name='maximum_stake_amount',
            field=models.DecimalField(decimal_places=8, max_digits=20),
        ),
        migrations.AlterField(
            model_name='stakeplan',
            name='minimum_stake_amount',
            field=models.DecimalField(decimal_places=8, max_digits=20),
        ),
    ]
