# Generated by Django 5.0.3 on 2024-04-05 08:49

import easy_thumbnails.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='E.g Ripple,Ethereum,US Dollar,Bitcoin,Euro', max_length=20, unique=True)),
                ('symbol', models.CharField(help_text='E.g XRP,ETH,USD,BTC,EUR', max_length=10, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', easy_thumbnails.fields.ThumbnailerImageField(default='default_currency_icon.png', help_text='Picture of the Currency, the picture should not have background. That is .png format', upload_to='currency_icons/')),
                ('is_crypto', models.BooleanField(default=True, help_text='To differentiate coin from fiat')),
                ('is_active', models.BooleanField(default=True, help_text='If asset should be display or not ')),
                ('payment_address', models.CharField(help_text='Wallet address to receive manual payment for this Currency', max_length=300)),
                ('barcode', easy_thumbnails.fields.ThumbnailerImageField(upload_to='payment_address')),
            ],
            options={
                'verbose_name_plural': 'Currencies',
            },
        ),
    ]
