# Generated by Django 5.0.4 on 2024-07-03 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0002_auto_20240407_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='payment_address',
            field=models.CharField(help_text='Wallet address to receive payment for this Currency', max_length=300),
        ),
    ]
