# Generated by Django 5.0.4 on 2024-07-03 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0003_alter_currency_payment_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currency',
            name='description',
        ),
        migrations.AddField(
            model_name='currency',
            name='address_prefix',
            field=models.CharField(blank=True, help_text='What comes b4 the address', max_length=10, null=True),
        ),
    ]
