# Generated by Django 5.0.4 on 2024-10-23 08:32

import easy_thumbnails.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0004_remove_currency_description_currency_address_prefix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='barcode',
            field=easy_thumbnails.fields.ThumbnailerImageField(help_text='Barcode of the wallet address to receive payment ', upload_to='payment_address'),
        ),
        migrations.AlterField(
            model_name='currency',
            name='payment_address',
            field=models.CharField(help_text='Wallet address to receive payment/deposit for this Currency', max_length=300),
        ),
    ]
