# Generated by Django 5.0.4 on 2025-01-24 11:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0006_alter_currency_percentage_deposit_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='minimum_withdraw',
            field=models.DecimalField(decimal_places=8, default=1e-07, max_digits=20, validators=[django.core.validators.MinValueValidator(1e-07)]),
        ),
    ]
