# Generated by Django 3.2.25 on 2024-04-07 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0003_alter_trade_trade_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='trade_id',
            field=models.CharField(default='#Y6CHFA9PB3', max_length=50),
        ),
    ]
