# Generated by Django 5.0.4 on 2024-07-03 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0011_alter_trade_trade_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='trade_id',
            field=models.CharField(default='#GMB4Z811SJ', max_length=50),
        ),
    ]
