# Generated by Django 5.0.4 on 2024-07-03 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0012_alter_trade_trade_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='trade_id',
            field=models.CharField(default='#I5UBR3IJ5R', max_length=50),
        ),
    ]
