# Generated by Django 5.0.4 on 2024-07-04 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0013_alter_trade_trade_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='trade_id',
            field=models.CharField(default='#A0K0I8P23H', max_length=50),
        ),
    ]
