# Generated by Django 5.0.4 on 2024-07-18 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0014_alter_trade_trade_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='trade_id',
            field=models.CharField(default='#S6FGN86KC1', max_length=50),
        ),
    ]
