# Generated by Django 5.0.4 on 2024-10-23 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0015_alter_trade_trade_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='trade_id',
            field=models.CharField(default='#KF6LREPACE', max_length=50),
        ),
    ]
