# Generated by Django 5.0.4 on 2025-01-10 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0016_alter_trade_trade_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='trade_id',
            field=models.CharField(default='#0Y0YRRNP0N', max_length=50),
        ),
    ]
