# Generated by Django 5.0.4 on 2025-01-11 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0017_alter_trade_trade_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='trade_id',
            field=models.CharField(default='#LYNMGUHJ3G', max_length=50),
        ),
    ]
