# Generated by Django 5.0.4 on 2025-01-16 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0018_alter_trade_trade_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='expected_payout',
            field=models.DecimalField(blank=True, decimal_places=8, default=0.0, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='trade',
            name='trade_id',
            field=models.CharField(default='#87T9R9Y6BR', max_length=50),
        ),
        migrations.AlterField(
            model_name='trade',
            name='trading_amount',
            field=models.DecimalField(decimal_places=8, max_digits=20),
        ),
    ]
