# Generated by Django 5.0.4 on 2025-01-17 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0019_alter_trade_expected_payout_alter_trade_trade_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='trade_id',
            field=models.CharField(default='#A53DPHV9Q4', max_length=50),
        ),
    ]
