# Generated by Django 5.0.4 on 2025-01-24 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0024_alter_trade_trade_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='trade_id',
            field=models.CharField(default='#3D24IMQEHX', max_length=50),
        ),
    ]
