# Generated by Django 5.0.4 on 2025-02-26 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0026_alter_trade_trade_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='trade_id',
            field=models.CharField(default='#D8CAEGOL2M', max_length=50),
        ),
    ]
