# Generated by Django 5.0.3 on 2024-04-05 08:49

import django.utils.timezone
import easy_thumbnails.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LaunchPad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin_name', models.CharField(help_text='E.g Ripple,Ethereum,US Dollar,Bitcoin,Euro', max_length=20, unique=True)),
                ('coin_symbol', models.CharField(help_text='E.g XRP,ETH,USD,BTC,EUR', max_length=10, unique=True)),
                ('description', models.TextField(blank=True)),
                ('coin_icon', easy_thumbnails.fields.ThumbnailerImageField(upload_to='launchpads/')),
                ('status', models.CharField(choices=[('active', 'Active'), ('upcoming', 'Upcoming'), ('completed', 'Completed')], default='upcoming', max_length=80)),
                ('soft_cap', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('hard_cap', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('sale_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('launch_time_start', models.DateTimeField(default=django.utils.timezone.now)),
                ('launch_time_end', models.DateTimeField(default=django.utils.timezone.now)),
                ('filled_percent', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ['-launch_time_start'],
            },
        ),
    ]
