# Generated by Django 5.0.3 on 2024-04-05 08:49

import django.utils.timezone
import easy_thumbnails.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CopyTrader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Copy Trader full name ', max_length=20, unique=True)),
                ('photo', easy_thumbnails.fields.ThumbnailerImageField(help_text='Picture of the CopyTrader', upload_to='copy_trader/')),
                ('no_wins', models.PositiveIntegerField(default=0)),
                ('no_loose', models.PositiveIntegerField(default=0)),
                ('no_copiers', models.PositiveIntegerField(default=0)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-date_joined'],
            },
        ),
    ]
