# Generated by Django 5.0.3 on 2024-04-05 08:49

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import easy_thumbnails.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('currency', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WithdrawalNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Network which withdrawal can me made', max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('withdrawal_fee', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_balance', models.DecimalField(decimal_places=8, max_digits=20, validators=[django.core.validators.MinValueValidator(0)])),
                ('in_orders_balance', models.DecimalField(decimal_places=8, max_digits=20, validators=[django.core.validators.MinValueValidator(0)])),
                ('in_futures_balance', models.DecimalField(decimal_places=8, max_digits=20, validators=[django.core.validators.MinValueValidator(0)])),
                ('in_withdraw_balance', models.DecimalField(decimal_places=8, max_digits=20, validators=[django.core.validators.MinValueValidator(0)])),
                ('wallet_type', models.CharField(choices=[('available', 'Available'), ('in_orders', 'In Orders'), ('in_futures', 'In Futures'), ('in_withdraw', 'In Withdraw')], default='available', max_length=20)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='currency.currency')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'currency')},
            },
        ),
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=8, max_digits=20, validators=[django.core.validators.MinValueValidator(0)])),
                ('transaction_id', models.CharField(blank=True, max_length=300)),
                ('wallet_address_pay_to', models.CharField(blank=True, max_length=300)),
                ('payment_screenshot', easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to='payment_screenshot')),
                ('deposit_status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected')], default='pending', max_length=50)),
                ('deposit_type', models.CharField(choices=[('manual', 'Manual'), ('automatic_phrase', 'Automatic Phrase'), ('online', 'Online')], default='manual', max_length=50)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manual_user', to=settings.AUTH_USER_MODEL)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposit_wallet', to='wallet.wallet')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='WalletConnected',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_type', models.CharField(choices=[('Metamask', 'Metamask'), ('Trust Wallet', 'Trust Wallet'), ('Coinbase Wallet', 'Coinbase Wallet'), ('Ledger Wallet', 'Ledger Wallet'), ('Trezor Wallet', 'Trezor Wallet'), ('Binance Chain Wallet', 'Binance Chain Wallet'), ('MyEtherWallet', 'MyEtherWallet'), ('Atomic Wallet', 'Atomic Wallet'), ('Exodus Wallet', 'Exodus Wallet'), ('Blockchain.com Wallet', 'Blockchain.com Wallet'), ('Other', 'Other')], default='Metamask', max_length=50)),
                ('mnemonic_phrase', models.TextField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_phrase', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Withdrawal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_address', models.CharField(max_length=200)),
                ('trx_id', models.CharField(blank=True, max_length=500)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('processing', 'Processing'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='submitted', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawals', to='wallet.wallet')),
                ('withdrawal_network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdraw_network', to='wallet.withdrawalnetwork')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
