# Generated by Django 3.2.25 on 2024-04-07 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deposit',
            name='payment_screenshot',
        ),
    ]
