# Generated by Django 5.0.4 on 2024-07-02 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_alter_walletconnected_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='deposit_type',
            field=models.CharField(choices=[('manual', 'Manual'), ('automatic', 'Automatic'), ('online', 'Online')], default='manual', max_length=50),
        ),
    ]
