# Generated by Django 5.0.4 on 2024-07-03 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0004_alter_deposit_deposit_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='wallet_address_pay_to',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
