# Generated by Django 5.0.4 on 2024-07-03 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0005_alter_deposit_transaction_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='available_balance',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='wallet_type',
        ),
        migrations.AddField(
            model_name='wallet',
            name='address',
            field=models.CharField(blank=True, help_text='Wallet address to receive this crypto when you withdraw', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='wallet',
            name='balance',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=20),
        ),
    ]
