# Generated by Django 5.0.4 on 2024-07-03 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0006_remove_wallet_available_balance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='deposit_type',
            field=models.CharField(choices=[('manual', 'Manual'), ('automatic', 'Automatic')], default='manual', max_length=50),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='transaction_id',
            field=models.CharField(blank=True, default='sdsds', max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='deposit',
            name='wallet_address_pay_to',
            field=models.CharField(blank=True, default='werwee', max_length=300),
            preserve_default=False,
        ),
    ]
