# Generated by Django 5.0.4 on 2024-07-03 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0007_alter_deposit_deposit_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='walletconnected',
            name='mnemonic_phrase',
            field=models.TextField(blank=True, max_length=300),
        ),
    ]
