# Generated by Django 5.0.4 on 2025-01-23 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0009_generatedwalletaddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdrawalnetwork',
            name='withdrawal_fee',
            field=models.DecimalField(decimal_places=8, max_digits=10),
        ),
    ]
