# Generated by Django 5.0.4 on 2025-01-27 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0010_alter_withdrawalnetwork_withdrawal_fee'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wallet',
            options={'ordering': ['user__username']},
        ),
    ]
